version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: buenro-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: buenro
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
    driver: local

